double genSin(double A, double f, double phase, double DC, double time);
double genSqr(double A, double f, double phase, double DC, double time);
// double genTri(double A, double f, double phase, double DC, double time);
void rangkaian1(double v[], double R, double C, double src, int i);
void rangkaian2(double v[], double R, double C, double src, int i);
void rangkaian3(double v1[],double v2[],double R, double C1, double C2, double Src, int i);
void rangkaian3V(double v1[], double v2[], double R, double C1, double C2, double Src, int i);
void rangkaian4(double v2[],double R1, double R2, double C, double Src[], int i);
void rangkaian4I(double v1[],double v2[],double R1, double R2, double C, double Is, int i);
void rangkaian5(double v2[],double R1, double R2, double C1, double C2, double Src[], int i);
void rangkaian5I(double v1[],double v2[],double R1, double R2, double C1, double C2, double Is, int i);
void rangkaian6(double v2[],double v3[],double R1, double R2, double C1, double C2, double Src[], int i);
void rangkaian6I(double v1[],double v2[],double v3[],double R1, double R2, double C1, double C2, double Src[], int i);
void rangkaian7(double v2[],double v3[],double R1, double R2, double C1, double C2, double Src[], int i);
void rangkaian7I(double v1[], double v2[],double v3[],double R1, double R2, double C1, double C2, double Src[], int i);
void rangkaian8(double v1[], double v2[], double v3[], double R1, double R2, double C1, double C2, double src, int i);
void rangkaian8V(double v1[], double v2[], double v3[], double R1, double R2, double C1, double C2, double src, int i);
